### PR TITLE
Updated ids method and Makefile for dkms

### PR DESCRIPTION
**Pull request by M0Rf30**
Hi,
as in title. In my latest commits, no edits where pulled to my repo, only a "renamed file" change. So this PR fixes definitively 4.14 compilations issues

### CODE REVIEW

**Comment by M0Rf30** [comment]
This will also fix https://github.com/astyonax/patched-RTS5227-5229/issues/4

**Comment by astyonax** [comment]
Hi,

I like the idea  and it is great that you already did so much 
but I have a couple of things I would like to see sorted out before merging:

 1.  The files of the driver are now dispersed in the main folder, which is not a good idea for future maintainability. They should go to a folder named, say: `rts5229/` . 
2.  If the scripts folder is useless, I would remove it. Same for every superfluous file ;)

If you say you have time to do it, great! Then I'll merge.
Otherwise I'll look for some time this weekend ;)

nice work! 
thank you again!

**Comment by M0Rf30** [comment]
Hi,
let me know if these changes are good for you. Although the driver is just patched, I've left patches folder in order to have a reference for cumulative changes.

**Comment by astyonax** [comment]
Thank you! I merged!

**Pull request merged**
